baseURL       = "https://omxpro.github.io/output/"
languageCode  = "en-us"
title         = "Om Senjalia | Portfolio"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Projects"
    url     = "projects"
    weight  = 3
  [[menu.nav]]
    name    = "Tools"
    url     = "tools"
    weight  = 4
  [[menu.nav]]
    name    = "Socials"
    url     = "socials"
    weight  = 5

  [[menu.nav]]
    name    = "Get in touch"
    url     = "contact"
    weight  = 6

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Roxo Hugo themes | Design Agency Template by StaticMania"
  author = "StaticMania"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/myykjpje"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Project Type"
    placeholder_about_the_project = "About the Project"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Graphics Design"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Web Design"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "Welcome to my portfolio! Thanks for stopping by!"
    tagline               = "Team work is Dream work!"
    secondary_button      = "Connect with Us"
    secondary_button_url  = "contact"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "Let's work together"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "Rickroll St.<br> india."
      phone   = "000-000-000"
      email   = "info@omxpro.cf"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About Me"
          url  = "about"
     [[params.footer.sitemap.link]]
          name = "Projects"
          url  = "projects"
     [[params.footer.sitemap.link]]
          name = "Tools i use"
          url  = "tools"
     [[params.footer.sitemap.link]]
          name = "Socials of mine"
          url  = "socials" 
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Medium"
          url  = "#"
        [[params.footer.social.link]]
          name = "Behance"
          url  = "#"
        [[params.footer.social.link]]
          name = "Dribbble"
          url  = "#"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "Thanks for visiting my Portfolio!"
        description = "Thanks for stopping by! This portfolio will be updated regularly to add more information. Thanks for visiting! I Hope to see you again!"
