baseURL = 'https://omxpro.github.io'
languageCode = 'en-us'
title = 'Hell There! i am Om Senjalia!'
theme = 'congo'

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'about me'
  url = '/about'
  weight = 2
